mosquitto:
  image: openenergy/rpi-mosquitto
  ports:
    - "1883:1883"
plugwise:
  image: openenergy/rpi-plugwise
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
  links:
    - mosquitto:mqtt
  volumes:
    - ../pw-conf.json:/opt/plugwise/config/pw-conf.json
    - ../pw-control.json:/opt/plugwise/config/pw-control.json
